### ISSUE TITLE
Getting "Precondition check failed." while approving entitlement

### ISSUE THREAD

**Issue by jp9573** [googlecodelabs/gcp-marketplace-integrated-saas#10]
When `ENTITLEMENT_ACTIVATION_REQUESTED` comes, it fails with the following message:

`File "/srv/account.py", line 140, in approve_entitlement request.execute() File "/env/lib/python3.7/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper return wrapped(*args, **kwargs) File "/env/lib/python3.7/site-packages/googleapiclient/http.py", line 856, in execute raise HttpError(resp, content, uri=self.uri) googleapiclient.errors.HttpError: <HttpError 400 when requesting https://cloudcommerceprocurement.googleapis.com/v1/providers/DEMO-dev-id/entitlements/98e15ffd-c538-428f-b92e-2cda2be98223:approve?alt=json returned "Precondition check failed.">`

Please help me with it, this is a major stopper.
Thanks in advance.

P.S. My code has the same implementation of `approve_entitlement` function.

**Comment by KishoreNamala** [comment]
The account needs to be in "APPROVED" sign up status before you approve an entitlement. Can you check ?

**Comment by jp9573** [comment]
Yes, that was the issue, seems that account approval request took place earlier and it failed due to some reasons and afterward I'm getting entitlement request only. 

I manually hit the approval endpoint and it works like a charm.
Thanks

**Comment by NivOclear** [comment]
this happen to me as well, and my account is approved
