### ISSUE TITLE
[marketplace-integrated-saas]: broken github links

### ISSUE THREAD

**Issue by pjain1** [googlecodelabs/gcp-marketplace-integrated-saas#11]
Many of the links pointing to github in the codelab tutorial are broken and gives 404. Few pages with broken links - 
1. https://codelabs.developers.google.com/codelabs/gcp-marketplace-integrated-saas/#4
2. https://codelabs.developers.google.com/codelabs/gcp-marketplace-integrated-saas/#5
3. https://codelabs.developers.google.com/codelabs/gcp-marketplace-integrated-saas/#6
4. https://codelabs.developers.google.com/codelabs/gcp-marketplace-integrated-saas/#7
5. https://codelabs.developers.google.com/codelabs/gcp-marketplace-integrated-saas/#8

**Comment by wt07** [comment]
We're working on a fix.

In the meantime, for most (if not all) of the broken links, all you have to do is change `python3.0` to `python3` in the path and it should work.
