### ISSUE TITLE
Missing import os causing error on line 20

### ISSUE THREAD

**Issue by KishoreNamala** [googlecodelabs/gcp-marketplace-integrated-saas#5]
https://github.com/googlecodelabs/gcp-marketplace-integrated-saas/blob/85ed4dd925287b972cc1cee19cfc1a85bfdfeeca/tools/create_subscription.py#L20

I can fix if OK with you.

**Comment by deci-ftw** [comment]
Fixed with https://github.com/googlecodelabs/gcp-marketplace-integrated-saas/commit/d5172efad9163ec44fdd1e4020dda470940fd1e9
