### ISSUE TITLE
TypeError: _get_account_name() takes exactly 1 argument (2 given) in reset_account

### ISSUE THREAD

**Issue by KishoreNamala** [googlecodelabs/gcp-marketplace-integrated-saas#7]
https://github.com/googlecodelabs/gcp-marketplace-integrated-saas/blob/d5172efad9163ec44fdd1e4020dda470940fd1e9/tools/reset_account.py#L40

PROJECT_ID isn't needed in the function call to _get_account_name() as its global.

**Comment by deci-ftw** [comment]
Fixed in https://github.com/googlecodelabs/gcp-marketplace-integrated-saas/pull/8
