### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by sabrinamamamia** [googlecodelabs/gcp-marketplace-integrated-saas#9]
Are there any plans to refactor this codelab to be in Python 3?

**Comment by tatemandel** [comment]
There's ongoing work currently for that. No ETA but should be pretty soon.

**Comment by sabrinamamamia** [comment]
Cool. I am implementing GCP Marketplace integration in NodeJS for an app. Could I make a NodeJS codelab when I am done?
